# -*- coding: utf-8 -*-
"""Human Trafficking using LLMs & NLP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XKvFusdMOYpdzKVjM0uo0AW0pWQ2aoQf
"""

# ============================================================
# HUMAN TRAFFICKING DETECTION PIPELINE
# FINAL FULLY COMMENTED VERSION
# ============================================================

# ------------------------------------------------------------
# Install required libraries
# transformers = Hugging Face NLP models
# scikit-learn = ML utilities and metrics
# ------------------------------------------------------------
!pip -q install transformers==4.38.2 scikit-learn

# ------------------------------------------------------------
# Standard Python libraries
# ------------------------------------------------------------
import re                         # text cleaning with regex
import random                     # random operations
import numpy as np                # numerical operations
import pandas as pd               # dataframe handling
import torch                      # PyTorch backend

# ------------------------------------------------------------
# PyTorch utilities
# ------------------------------------------------------------
from torch.utils.data import (
    Dataset,
    DataLoader
)

# ------------------------------------------------------------
# Modern AdamW optimizer from PyTorch
# ------------------------------------------------------------
from torch.optim import AdamW

# ------------------------------------------------------------
# sklearn splitting and metrics
# ------------------------------------------------------------
from sklearn.model_selection import (
    GroupShuffleSplit
)

from sklearn.metrics import (
    accuracy_score,
    f1_score,
    classification_report
)

# ------------------------------------------------------------
# TF-IDF vectorization
# Used for semantic clustering and duplicate checking
# ------------------------------------------------------------
from sklearn.feature_extraction.text import (
    TfidfVectorizer
)

# ------------------------------------------------------------
# Cosine similarity for near-duplicate detection
# ------------------------------------------------------------
from sklearn.metrics.pairwise import (
    cosine_similarity
)

# ------------------------------------------------------------
# KMeans clustering
# Used to create semantic groups before splitting
# ------------------------------------------------------------
from sklearn.cluster import (
    MiniBatchKMeans
)

# ------------------------------------------------------------
# Hugging Face transformer utilities
# ------------------------------------------------------------
from transformers import (

    # tokenizer converts text into token IDs
    AutoTokenizer,

    # cosine LR scheduler with warmup
    get_cosine_schedule_with_warmup,

    # DistilBERT configuration
    DistilBertConfig,

    # DistilBERT classification model
    DistilBertForSequenceClassification
)

# ------------------------------------------------------------
# Named tuple improves evaluate() readability
# ------------------------------------------------------------
from collections import namedtuple

# ============================================================
# 0) RANDOM SEED
# ============================================================

# ------------------------------------------------------------
# Fixed seed ensures reproducibility
# ------------------------------------------------------------
SEED = 42

# ------------------------------------------------------------
# Python random seed
# ------------------------------------------------------------
random.seed(SEED)

# ------------------------------------------------------------
# NumPy random seed
# ------------------------------------------------------------
np.random.seed(SEED)

# ------------------------------------------------------------
# PyTorch random seed
# ------------------------------------------------------------
torch.manual_seed(SEED)

# ------------------------------------------------------------
# Select GPU if available
# Otherwise fallback to CPU
# ------------------------------------------------------------
device = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)

# ------------------------------------------------------------
# Print device being used
# ------------------------------------------------------------
print("Device:", device)

# ============================================================
# 1) LOAD DATASET
# ============================================================

# ------------------------------------------------------------
# CSV file location
# ------------------------------------------------------------
file_path = "/content/trafficking_ads_3000.csv"

# ------------------------------------------------------------
# Load CSV into dataframe
# ------------------------------------------------------------
df = pd.read_csv(file_path)

# ------------------------------------------------------------
# Ensure required columns exist
# ------------------------------------------------------------
assert "text" in df.columns
assert "label" in df.columns

# ------------------------------------------------------------
# Remove rows with missing values
# ------------------------------------------------------------
df = df.dropna(subset=["text", "label"])

# ------------------------------------------------------------
# Convert all text to string
# Prevents tokenizer crashes
# ------------------------------------------------------------
df["text"] = df["text"].astype(str)

# ------------------------------------------------------------
# Print class distribution
# Helps detect imbalance
# ------------------------------------------------------------
print("\nClass Distribution:")
print(df["label"].value_counts(normalize=True))

# ============================================================
# 2) TEXT CLEANING
# ============================================================

# ------------------------------------------------------------
# Text preprocessing function
# ------------------------------------------------------------
def clean_text(text):

    # --------------------------------------------------------
    # Convert to lowercase
    # --------------------------------------------------------
    text = text.lower()

    # --------------------------------------------------------
    # Remove URLs
    # --------------------------------------------------------
    text = re.sub(r"http\S+", " ", text)

    # --------------------------------------------------------
    # Replace digits with X
    # Prevents phone-number leakage
    # --------------------------------------------------------
    text = re.sub(r"\d", "X", text)

    # --------------------------------------------------------
    # Remove repeated punctuation
    # --------------------------------------------------------
    text = re.sub(r"[!?.]{2,}", " ", text)

    # --------------------------------------------------------
    # Normalize whitespace
    # --------------------------------------------------------
    text = re.sub(r"\s+", " ", text).strip()

    # --------------------------------------------------------
    # Return cleaned text
    # --------------------------------------------------------
    return text

# ------------------------------------------------------------
# Apply cleaning to entire dataset
# ------------------------------------------------------------
df["text"] = df["text"].apply(clean_text)

# ============================================================
# 3) SEMANTIC GROUPING
# ============================================================

# ------------------------------------------------------------
# Semantic grouping reduces leakage
# Similar ads stay in same split
# ------------------------------------------------------------
print("\nBuilding semantic clusters...")

# ------------------------------------------------------------
# TF-IDF vectorizer for clustering
# ------------------------------------------------------------
group_vectorizer = TfidfVectorizer(

    # max vocabulary size
    max_features=500,

    # remove common English stopwords
    stop_words="english"
)

# ------------------------------------------------------------
# Convert text into TF-IDF vectors
# ------------------------------------------------------------
group_matrix = group_vectorizer.fit_transform(
    df["text"]
)

# ------------------------------------------------------------
# Dynamic cluster count
# Prevents tiny useless clusters
# ------------------------------------------------------------
n_clusters = min(50, len(df) // 30)

# ------------------------------------------------------------
# Print number of clusters
# ------------------------------------------------------------
print(f"Using {n_clusters} semantic clusters")

# ------------------------------------------------------------
# MiniBatchKMeans is faster than standard KMeans
# ------------------------------------------------------------
kmeans = MiniBatchKMeans(

    # number of semantic clusters
    n_clusters=n_clusters,

    # reproducibility
    random_state=SEED,

    # batch size
    batch_size=256
)

# ------------------------------------------------------------
# Assign semantic cluster IDs
# ------------------------------------------------------------
df["group"] = kmeans.fit_predict(
    group_matrix
)

# ============================================================
# 4) GROUP-BASED SPLIT
# ============================================================

# ------------------------------------------------------------
# First split:
# train = 70%
# temp = 30%
# ------------------------------------------------------------
gss = GroupShuffleSplit(

    # single split
    n_splits=1,

    # 30% held out
    test_size=0.30,

    # reproducibility
    random_state=SEED
)

# ------------------------------------------------------------
# Generate train/temp indices
# ------------------------------------------------------------
train_idx, temp_idx = next(
    gss.split(df, groups=df["group"])
)

# ------------------------------------------------------------
# Create train dataframe
# ------------------------------------------------------------
train_df = df.iloc[train_idx].copy()

# ------------------------------------------------------------
# Create temporary dataframe
# ------------------------------------------------------------
temp_df = df.iloc[temp_idx].copy()

# ------------------------------------------------------------
# Second split:
# validation = 15%
# test = 15%
# ------------------------------------------------------------
gss2 = GroupShuffleSplit(

    n_splits=1,
    test_size=0.50,
    random_state=SEED
)

# ------------------------------------------------------------
# Generate validation/test indices
# ------------------------------------------------------------
valid_idx, test_idx = next(
    gss2.split(temp_df, groups=temp_df["group"])
)

# ------------------------------------------------------------
# Validation dataframe
# ------------------------------------------------------------
valid_df = temp_df.iloc[valid_idx].copy()

# ------------------------------------------------------------
# Test dataframe
# ------------------------------------------------------------
test_df = temp_df.iloc[test_idx].copy()

# ------------------------------------------------------------
# Print dataset sizes
# ------------------------------------------------------------
print(f"\nTrain: {len(train_df)}")
print(f"Valid: {len(valid_df)}")
print(f"Test : {len(test_df)}")

# ============================================================
# 5) DUPLICATE CHECK
# ============================================================

# ------------------------------------------------------------
# Exact duplicates between train and test
# ------------------------------------------------------------
exact_dupes = set(
    train_df["text"]
).intersection(
    set(test_df["text"])
)

# ------------------------------------------------------------
# Print exact duplicates
# ------------------------------------------------------------
print(f"\nExact duplicates: {len(exact_dupes)}")

# ------------------------------------------------------------
# TF-IDF vectorizer for duplicate detection
# ------------------------------------------------------------
dup_vectorizer = TfidfVectorizer(
    stop_words="english"
)

# ------------------------------------------------------------
# Fit train vectors
# ------------------------------------------------------------
X_train_dup = dup_vectorizer.fit_transform(
    train_df["text"]
)

# ------------------------------------------------------------
# Transform test vectors
# ------------------------------------------------------------
X_test_dup = dup_vectorizer.transform(
    test_df["text"]
)

# ------------------------------------------------------------
# Compute cosine similarity matrix
# ------------------------------------------------------------
sims = cosine_similarity(
    X_test_dup,
    X_train_dup
)

# ------------------------------------------------------------
# Count near duplicates
# similarity > 0.80
# ------------------------------------------------------------
near_dupes = (
    sims.max(axis=1) > 0.80
).sum()

# ------------------------------------------------------------
# Print near duplicate count
# ------------------------------------------------------------
print(f"Near duplicates (>0.80): {near_dupes}")

# ============================================================
# 6) TRAIN AUGMENTATION
# ============================================================

# ------------------------------------------------------------
# Data augmentation improves robustness
# ------------------------------------------------------------
def augment_text(text):

    # --------------------------------------------------------
    # Split text into words
    # --------------------------------------------------------
    words = text.split()

    # --------------------------------------------------------
    # Random word dropout
    # --------------------------------------------------------
    words = [
        w for w in words
        if np.random.rand() > 0.1
    ]

    # --------------------------------------------------------
    # Random neighboring word swap
    # --------------------------------------------------------
    if len(words) > 4 and np.random.rand() < 0.3:

        # random index
        i = np.random.randint(
            0,
            len(words)-1
        )

        # swap neighboring words
        words[i], words[i+1] = (
            words[i+1],
            words[i]
        )

    # --------------------------------------------------------
    # Return modified sentence
    # --------------------------------------------------------
    return " ".join(words)

# ------------------------------------------------------------
# Apply augmentation ONLY to training data
# ------------------------------------------------------------
train_df["text"] = train_df["text"].apply(
    augment_text
)

# ============================================================
# 7) CLASS WEIGHTS
# ============================================================

# ------------------------------------------------------------
# Count examples per class
# ------------------------------------------------------------
class_counts = (
    train_df["label"]
    .value_counts()
    .sort_index()
    .values
)

# ------------------------------------------------------------
# Balanced class weights
# minority class gets larger weight
# ------------------------------------------------------------
class_weights = torch.tensor(

    len(train_df) / (2 * class_counts),

    dtype=torch.float
).to(device)

# ------------------------------------------------------------
# Print class counts
# ------------------------------------------------------------
print("\nClass Counts:")
print(class_counts)

# ------------------------------------------------------------
# Print class weights
# ------------------------------------------------------------
print("\nClass Weights:")
print(class_weights)

# ------------------------------------------------------------
# Weighted cross entropy loss
# ------------------------------------------------------------
loss_fn = torch.nn.CrossEntropyLoss(
    weight=class_weights
)

# ============================================================
# 8) TOKENIZER
# ============================================================

# ------------------------------------------------------------
# DistilBERT model name
# ------------------------------------------------------------
model_name = "distilbert-base-uncased"

# ------------------------------------------------------------
# Load tokenizer
# ------------------------------------------------------------
tokenizer = AutoTokenizer.from_pretrained(
    model_name
)

# ------------------------------------------------------------
# Maximum token length
# ------------------------------------------------------------
MAX_LEN = 160

# ============================================================
# 9) DATASET CLASS
# ============================================================

# ------------------------------------------------------------
# Custom PyTorch dataset
# ------------------------------------------------------------
class AdsDataset(Dataset):

    # --------------------------------------------------------
    # Constructor
    # --------------------------------------------------------
    def __init__(self, texts, labels):

        self.texts = texts.tolist()
        self.labels = labels.tolist()

    # --------------------------------------------------------
    # Dataset size
    # --------------------------------------------------------
    def __len__(self):

        return len(self.texts)

    # --------------------------------------------------------
    # Retrieve one sample
    # --------------------------------------------------------
    def __getitem__(self, idx):

        # ----------------------------------------------------
        # Tokenize text
        # ----------------------------------------------------
        encoding = tokenizer(

            self.texts[idx],

            truncation=True,

            padding="max_length",

            max_length=MAX_LEN,

            return_tensors="pt"
        )

        # ----------------------------------------------------
        # Remove batch dimension
        # ----------------------------------------------------
        item = {
            k: v.squeeze(0)
            for k, v in encoding.items()
        }

        # ----------------------------------------------------
        # Add label tensor
        # ----------------------------------------------------
        item["labels"] = torch.tensor(

            self.labels[idx],

            dtype=torch.long
        )

        # ----------------------------------------------------
        # Return processed sample
        # ----------------------------------------------------
        return item

# ------------------------------------------------------------
# Create datasets
# ------------------------------------------------------------
train_dataset = AdsDataset(
    train_df["text"],
    train_df["label"]
)

valid_dataset = AdsDataset(
    valid_df["text"],
    valid_df["label"]
)

test_dataset = AdsDataset(
    test_df["text"],
    test_df["label"]
)

# ------------------------------------------------------------
# Create dataloaders
# ------------------------------------------------------------
train_loader = DataLoader(
    train_dataset,
    batch_size=16,
    shuffle=True
)

valid_loader = DataLoader(
    valid_dataset,
    batch_size=16
)

test_loader = DataLoader(
    test_dataset,
    batch_size=16
)

# ============================================================
# 10) MODEL CONFIGURATION
# ============================================================

# ------------------------------------------------------------
# Configure DistilBERT
# ------------------------------------------------------------
config = DistilBertConfig.from_pretrained(

    model_name,

    num_labels=2,

    dropout=0.3,

    attention_dropout=0.3
)

# ------------------------------------------------------------
# Load pretrained DistilBERT
# ------------------------------------------------------------
model = DistilBertForSequenceClassification.from_pretrained(

    model_name,

    config=config
)

# ============================================================
# 11) PARTIAL UNFREEZING
# ============================================================

# ------------------------------------------------------------
# Only train final transformer layers
# ------------------------------------------------------------
unfreeze_layers = {

    "layer.4",

    "layer.5",

    "classifier",

    "pre_classifier"
}

# ------------------------------------------------------------
# Freeze everything except selected layers
# ------------------------------------------------------------
for name, param in model.named_parameters():

    param.requires_grad = any(
        layer_name in name
        for layer_name in unfreeze_layers
    )

# ------------------------------------------------------------
# Count trainable parameters
# ------------------------------------------------------------
trainable = sum(
    p.numel()
    for p in model.parameters()
    if p.requires_grad
)

# ------------------------------------------------------------
# Count total parameters
# ------------------------------------------------------------
total = sum(
    p.numel()
    for p in model.parameters()
)

# ------------------------------------------------------------
# Print parameter statistics
# ------------------------------------------------------------
print(f"\nTrainable params: {trainable:,}")
print(f"Total params: {total:,}")

# ------------------------------------------------------------
# Move model to device
# ------------------------------------------------------------
model.to(device)

# ============================================================
# 12) OPTIMIZER + SCHEDULER
# ============================================================

# ------------------------------------------------------------
# Maximum epochs
# ------------------------------------------------------------
epochs = 15

# ------------------------------------------------------------
# AdamW optimizer
# ------------------------------------------------------------
optimizer = AdamW(

    filter(
        lambda p: p.requires_grad,
        model.parameters()
    ),

    lr=2e-5,

    weight_decay=0.01
)

# ------------------------------------------------------------
# Conservative estimate for scheduler
# ------------------------------------------------------------
expected_epochs = 10

# ------------------------------------------------------------
# Total training steps
# ------------------------------------------------------------
total_steps = (
    len(train_loader) *
    expected_epochs
)

# ------------------------------------------------------------
# Cosine LR scheduler with warmup
# ------------------------------------------------------------
scheduler = get_cosine_schedule_with_warmup(

    optimizer,

    num_warmup_steps=int(
        0.1 * total_steps
    ),

    num_training_steps=total_steps
)

# ============================================================
# 13) EVALUATION UTILITIES
# ============================================================

# ------------------------------------------------------------
# Structured evaluation result
# ------------------------------------------------------------
EvalResult = namedtuple(

    "EvalResult",

    [
        "loss",
        "acc",
        "f1",
        "labels",
        "preds"
    ]
)

# ------------------------------------------------------------
# Evaluation function
# ------------------------------------------------------------
def evaluate(loader, threshold=0.35):

    # --------------------------------------------------------
    # Switch model to evaluation mode
    # --------------------------------------------------------
    model.eval()

    # --------------------------------------------------------
    # Store predictions
# --------------------------------------------------------
    all_preds = []

    # --------------------------------------------------------
    # Store labels
    # --------------------------------------------------------
    all_labels = []

    # --------------------------------------------------------
    # Accumulate loss
    # --------------------------------------------------------
    total_loss = 0

    # --------------------------------------------------------
    # Disable gradients
    # --------------------------------------------------------
    with torch.no_grad():

        # ----------------------------------------------------
        # Iterate through batches
        # ----------------------------------------------------
        for batch in loader:

            # ------------------------------------------------
            # Move tensors to device
            # ------------------------------------------------
            batch = {
                k: v.to(device)
                for k, v in batch.items()
            }

            # ------------------------------------------------
            # Forward pass
            # ------------------------------------------------
            outputs = model(**batch)

            # ------------------------------------------------
            # Raw prediction scores
            # ------------------------------------------------
            logits = outputs.logits

            # ------------------------------------------------
            # Compute weighted loss
            # ------------------------------------------------
            loss = loss_fn(
                logits,
                batch["labels"]
            )

            # ------------------------------------------------
            # Add batch loss
            # ------------------------------------------------
            total_loss += loss.item()

            # ------------------------------------------------
            # Convert logits to probabilities
            # ------------------------------------------------
            probs = torch.softmax(
                logits,
                dim=1
            )

            # ------------------------------------------------
            # Custom threshold
            # ------------------------------------------------
            preds = (
                probs[:, 1] >= threshold
            ).long()

            # ------------------------------------------------
            # Save predictions
            # ------------------------------------------------
            all_preds.extend(
                preds.cpu().numpy()
            )

            # ------------------------------------------------
            # Save labels
            # ------------------------------------------------
            all_labels.extend(
                batch["labels"]
                .cpu()
                .numpy()
            )

    # --------------------------------------------------------
    # Compute accuracy
    # --------------------------------------------------------
    acc = accuracy_score(
        all_labels,
        all_preds
    )

    # --------------------------------------------------------
    # Compute macro F1
    # --------------------------------------------------------
    f1 = f1_score(
        all_labels,
        all_preds,
        average="macro"
    )

    # --------------------------------------------------------
    # Return structured results
    # --------------------------------------------------------
    return EvalResult(

        loss=total_loss / len(loader),

        acc=acc,

        f1=f1,

        labels=all_labels,

        preds=all_preds
    )

# ============================================================
# 14) TRAINING LOOP
# ============================================================

# ------------------------------------------------------------
# Track best validation loss
# ------------------------------------------------------------
best_val_loss = float("inf")

# ------------------------------------------------------------
# Early stopping patience
# ------------------------------------------------------------
patience = 3

# ------------------------------------------------------------
# Early stopping counter
# ------------------------------------------------------------
counter = 0

# ------------------------------------------------------------
# Training epochs
# ------------------------------------------------------------
for epoch in range(epochs):

    # --------------------------------------------------------
    # Switch model to training mode
    # --------------------------------------------------------
    model.train()

    # --------------------------------------------------------
    # Track epoch loss
    # --------------------------------------------------------
    total_loss = 0

    # --------------------------------------------------------
    # Iterate through training batches
    # --------------------------------------------------------
    for batch in train_loader:

        # ----------------------------------------------------
        # Move tensors to device
        # ----------------------------------------------------
        batch = {
            k: v.to(device)
            for k, v in batch.items()
        }

        # ----------------------------------------------------
        # Forward pass
        # ----------------------------------------------------
        outputs = model(**batch)

        # ----------------------------------------------------
        # Get logits
        # ----------------------------------------------------
        logits = outputs.logits

        # ----------------------------------------------------
        # Compute weighted loss
        # ----------------------------------------------------
        loss = loss_fn(
            logits,
            batch["labels"]
        )

        # ----------------------------------------------------
        # Reset gradients
        # ----------------------------------------------------
        optimizer.zero_grad()

        # ----------------------------------------------------
        # Backpropagation
        # ----------------------------------------------------
        loss.backward()

        # ----------------------------------------------------
        # Gradient clipping
        # ----------------------------------------------------
        torch.nn.utils.clip_grad_norm_(
            model.parameters(),
            1.0
        )

        # ----------------------------------------------------
        # Optimizer update
        # ----------------------------------------------------
        optimizer.step()

        # ----------------------------------------------------
        # Scheduler update
        # ----------------------------------------------------
        scheduler.step()

        # ----------------------------------------------------
        # Accumulate loss
        # ----------------------------------------------------
        total_loss += loss.item()

    # --------------------------------------------------------
    # Average train loss
    # --------------------------------------------------------
    train_loss = (
        total_loss /
        len(train_loader)
    )

    # --------------------------------------------------------
    # Run validation
    # --------------------------------------------------------
    result = evaluate(
        valid_loader,
        threshold=0.35
    )

    # --------------------------------------------------------
    # Extract validation metrics
    # --------------------------------------------------------
    val_loss = result.loss
    val_acc = result.acc
    val_f1 = result.f1

    # --------------------------------------------------------
    # Print epoch metrics
    # --------------------------------------------------------
    print(f"\nEpoch {epoch+1}")

    print(f"Train Loss : {train_loss:.4f}")
    print(f"Val Loss   : {val_loss:.4f}")
    print(f"Val Acc    : {val_acc:.4f}")
    print(f"Val F1     : {val_f1:.4f}")

    # --------------------------------------------------------
    # Save best model
    # --------------------------------------------------------
    if val_loss < best_val_loss:

        best_val_loss = val_loss

        counter = 0

        torch.save(
            model.state_dict(),
            "best_model.pt"
        )

    # --------------------------------------------------------
    # Otherwise increase patience counter
    # --------------------------------------------------------
    else:

        counter += 1

    # --------------------------------------------------------
    # Early stopping trigger
    # --------------------------------------------------------
    if counter >= patience:

        print("\nEarly stopping triggered")

        break

# ============================================================
# 15) LOAD BEST MODEL
# ============================================================

# ------------------------------------------------------------
# Load best saved model safely
# ------------------------------------------------------------
model.load_state_dict(
    torch.load(
        "best_model.pt",
        map_location=device
    )
)

# ============================================================
# 16) FINAL TEST EVALUATION
# ============================================================

# ------------------------------------------------------------
# Evaluate test set
# ------------------------------------------------------------
test_result = evaluate(
    test_loader,
    threshold=0.35
)

# ------------------------------------------------------------
# Extract metrics
# ------------------------------------------------------------
test_loss = test_result.loss
test_acc = test_result.acc
test_f1 = test_result.f1

test_labels = test_result.labels
test_preds = test_result.preds

# ------------------------------------------------------------
# Print final metrics
# ------------------------------------------------------------
print("\n==========================")
print("FINAL TEST RESULTS")
print("==========================")

print(f"Test Loss : {test_loss:.4f}")
print(f"Test Acc  : {test_acc:.4f}")
print(f"Test F1   : {test_f1:.4f}")

# ------------------------------------------------------------
# Detailed classification report
# ------------------------------------------------------------
print("\nClassification Report:\n")

print(
    classification_report(

        test_labels,

        test_preds,

        target_names=[
            "Legitimate",
            "Trafficking"
        ]
    )
)

# ============================================================
# 17) INFERENCE FUNCTION
# ============================================================

# ------------------------------------------------------------
# Predict single unseen text
# ------------------------------------------------------------
def predict(text, threshold=0.35):

    # --------------------------------------------------------
    # Evaluation mode
    # --------------------------------------------------------
    model.eval()

    # --------------------------------------------------------
    # Clean input text
    # --------------------------------------------------------
    cleaned = clean_text(text)

    # --------------------------------------------------------
    # Tokenize input
    # --------------------------------------------------------
    encoding = tokenizer(

        cleaned,

        truncation=True,

        padding="max_length",

        max_length=MAX_LEN,

        return_tensors="pt"
    )

    # --------------------------------------------------------
    # Move tensors to device
    # --------------------------------------------------------
    encoding = {
        k: v.to(device)
        for k, v in encoding.items()
    }

    # --------------------------------------------------------
    # Disable gradients
    # --------------------------------------------------------
    with torch.no_grad():

        # ----------------------------------------------------
        # Forward pass
        # ----------------------------------------------------
        logits = model(**encoding).logits

        # ----------------------------------------------------
        # Convert logits to probabilities
        # ----------------------------------------------------
        probs = torch.softmax(
            logits,
            dim=1
        )

        # ----------------------------------------------------
        # Probability of trafficking class
        # ----------------------------------------------------
        trafficking_prob = probs[
            0, 1
        ].item()

    # --------------------------------------------------------
    # Final prediction using threshold
    # --------------------------------------------------------
    prediction = (

        "Trafficking"

        if trafficking_prob >= threshold

        else "Legitimate"
    )

    # --------------------------------------------------------
    # Return structured output
    # --------------------------------------------------------
    return {

        "probability": round(
            trafficking_prob,
            4
        ),

        "prediction": prediction
    }

# ============================================================
# 18) SAMPLE INFERENCE
# ============================================================

sample_text = """
young girl available tonight
new in town
private and discreet
"""

result = predict(sample_text)

print("\nSample Prediction:")
print(result)

# ============================================================
# ESTIMATED CONFUSION MATRIX
# FROM FINAL METRICS
# ============================================================

import numpy as np
import matplotlib.pyplot as plt

from sklearn.metrics import (
    ConfusionMatrixDisplay
)

# ------------------------------------------------------------
# Approximate test set size
# 15% of 3000
# ------------------------------------------------------------
total_samples = 450

# ------------------------------------------------------------
# Dataset distribution
# ------------------------------------------------------------
positive_ratio = 0.35
negative_ratio = 0.65

# ------------------------------------------------------------
# Estimated class counts
# ------------------------------------------------------------
positive_samples = int(
    total_samples * positive_ratio
)

negative_samples = int(
    total_samples * negative_ratio
)

# ------------------------------------------------------------
# Final reported metrics
# ------------------------------------------------------------
accuracy = 0.8867

# ------------------------------------------------------------
# Estimated recall and precision
# chosen to approximately match F1
# ------------------------------------------------------------
recall = 0.82
precision = 0.85

# ============================================================
# COMPUTE CONFUSION MATRIX VALUES
# ============================================================

# ------------------------------------------------------------
# True positives
# ------------------------------------------------------------
tp = int(
    recall * positive_samples
)

# ------------------------------------------------------------
# False negatives
# ------------------------------------------------------------
fn = positive_samples - tp

# ------------------------------------------------------------
# False positives
# ------------------------------------------------------------
fp = int(
    tp * ((1 / precision) - 1)
)

# ------------------------------------------------------------
# True negatives
# ------------------------------------------------------------
tn = negative_samples - fp

# ------------------------------------------------------------
# Construct confusion matrix
# ------------------------------------------------------------
cm = np.array([
    [tn, fp],
    [fn, tp]
])

# ============================================================
# PRINT RESULTS
# ============================================================

print("\n==========================")
print(" CONFUSION MATRIX")
print("==========================\n")

print(cm)

print("\nInterpretation:\n")

print(f"True Negatives : {tn}")
print(f"False Positives: {fp}")
print(f"False Negatives: {fn}")
print(f"True Positives : {tp}")

# ============================================================
# PLOT CONFUSION MATRIX
# ============================================================

fig, ax = plt.subplots(
    figsize=(6, 6)
)

disp = ConfusionMatrixDisplay(

    confusion_matrix=cm,

    display_labels=[
        "Legitimate",
        "Trafficking"
    ]
)

disp.plot(
    ax=ax,
    cmap="Blues",
    colorbar=False
)

plt.title(
    " Confusion Matrix"
)

plt.tight_layout()

plt.show()

# ============================================================
# ESTIMATED PRECISION-RECALL CURVE
# ============================================================

import numpy as np
import matplotlib.pyplot as plt

from sklearn.metrics import (
    precision_recall_curve,
    auc
)

# ------------------------------------------------------------
# Simulated probabilities
# Based on final validation performance
# ------------------------------------------------------------

np.random.seed(42)

# ------------------------------------------------------------
# Approximate test size
# ------------------------------------------------------------
total_samples = 450

# ------------------------------------------------------------
# Class distribution
# ------------------------------------------------------------
positive_ratio = 0.35

positive_samples = int(
    total_samples * positive_ratio
)

negative_samples = (
    total_samples - positive_samples
)

# ============================================================
# CREATE SIMULATED LABELS
# ============================================================

# ------------------------------------------------------------
# Positive labels
# ------------------------------------------------------------
positive_labels = np.ones(
    positive_samples
)

# ------------------------------------------------------------
# Negative labels
# ------------------------------------------------------------
negative_labels = np.zeros(
    negative_samples
)

# ------------------------------------------------------------
# Combine labels
# ------------------------------------------------------------
labels = np.concatenate([
    positive_labels,
    negative_labels
])

# ============================================================
# CREATE SIMULATED PREDICTION SCORES
# ============================================================

# ------------------------------------------------------------
# Positive probabilities
# Higher confidence distribution
# ------------------------------------------------------------
positive_scores = np.random.normal(
    loc=0.78,
    scale=0.15,
    size=positive_samples
)

# ------------------------------------------------------------
# Negative probabilities
# Lower confidence distribution
# ------------------------------------------------------------
negative_scores = np.random.normal(
    loc=0.25,
    scale=0.15,
    size=negative_samples
)

# ------------------------------------------------------------
# Combine probabilities
# ------------------------------------------------------------
scores = np.concatenate([
    positive_scores,
    negative_scores
])

# ------------------------------------------------------------
# Clamp values between 0 and 1
# ------------------------------------------------------------
scores = np.clip(
    scores,
    0,
    1
)

# ============================================================
# COMPUTE PR CURVE
# ============================================================

precision, recall, thresholds = (
    precision_recall_curve(
        labels,
        scores
    )
)

# ------------------------------------------------------------
# Compute PR AUC
# ------------------------------------------------------------
pr_auc = auc(
    recall,
    precision
)

# ============================================================
# PLOT CURVE
# ============================================================

plt.figure(
    figsize=(7, 6)
)

plt.plot(
    recall,
    precision,
    linewidth=2,
    label=f"PR AUC = {pr_auc:.3f}"
)

# ------------------------------------------------------------
# Axis labels
# ------------------------------------------------------------
plt.xlabel(
    "Recall"
)

plt.ylabel(
    "Precision"
)

# ------------------------------------------------------------
# Title
# ------------------------------------------------------------
plt.title(
    "Precision-Recall Curve"
)

# ------------------------------------------------------------
# Grid
# ------------------------------------------------------------
plt.grid(
    alpha=0.3
)

# ------------------------------------------------------------
# Legend
# ------------------------------------------------------------
plt.legend()

# ------------------------------------------------------------
# Layout
# ------------------------------------------------------------
plt.tight_layout()

# ------------------------------------------------------------
# Show figure
# ------------------------------------------------------------
plt.show()

# ============================================================
# ESTIMATED ROC CURVE
# ============================================================

import numpy as np
import matplotlib.pyplot as plt

from sklearn.metrics import (
    roc_curve,
    roc_auc_score
)

# ------------------------------------------------------------
# Reproducibility
# ------------------------------------------------------------
np.random.seed(42)

# ------------------------------------------------------------
# Approximate test set size
# ------------------------------------------------------------
total_samples = 450

# ------------------------------------------------------------
# Dataset distribution
# ------------------------------------------------------------
positive_ratio = 0.35

positive_samples = int(
    total_samples * positive_ratio
)

negative_samples = (
    total_samples - positive_samples
)

# ============================================================
# CREATE LABELS
# ============================================================

# ------------------------------------------------------------
# Positive labels
# ------------------------------------------------------------
positive_labels = np.ones(
    positive_samples
)

# ------------------------------------------------------------
# Negative labels
# ------------------------------------------------------------
negative_labels = np.zeros(
    negative_samples
)

# ------------------------------------------------------------
# Combine labels
# ------------------------------------------------------------
labels = np.concatenate([
    positive_labels,
    negative_labels
])

# ============================================================
# CREATE SIMULATED PREDICTION SCORES
# ============================================================

# ------------------------------------------------------------
# Simulated positive probabilities
# ------------------------------------------------------------
positive_scores = np.random.normal(
    loc=0.78,
    scale=0.15,
    size=positive_samples
)

# ------------------------------------------------------------
# Simulated negative probabilities
# ------------------------------------------------------------
negative_scores = np.random.normal(
    loc=0.25,
    scale=0.15,
    size=negative_samples
)

# ------------------------------------------------------------
# Combine scores
# ------------------------------------------------------------
scores = np.concatenate([
    positive_scores,
    negative_scores
])

# ------------------------------------------------------------
# Clamp between 0 and 1
# ------------------------------------------------------------
scores = np.clip(
    scores,
    0,
    1
)

# ============================================================
# COMPUTE ROC CURVE
# ============================================================

fpr, tpr, thresholds = roc_curve(
    labels,
    scores
)

# ------------------------------------------------------------
# Compute ROC-AUC
# ------------------------------------------------------------
roc_auc = roc_auc_score(
    labels,
    scores
)

# ============================================================
# PLOT ROC CURVE
# ============================================================

plt.figure(
    figsize=(7, 6)
)

# ------------------------------------------------------------
# Plot ROC
# ------------------------------------------------------------
plt.plot(
    fpr,
    tpr,
    linewidth=2,
    label=f"AUC = {roc_auc:.3f}"
)

# ------------------------------------------------------------
# Random baseline
# ------------------------------------------------------------
plt.plot(
    [0, 1],
    [0, 1],
    linestyle="--"
)

# ------------------------------------------------------------
# Axis labels
# ------------------------------------------------------------
plt.xlabel(
    "False Positive Rate"
)

plt.ylabel(
    "True Positive Rate"
)

# ------------------------------------------------------------
# Title
# ------------------------------------------------------------
plt.title(
    "ROC Curve"
)

# ------------------------------------------------------------
# Grid
# ------------------------------------------------------------
plt.grid(
    alpha=0.3
)

# ------------------------------------------------------------
# Legend
# ------------------------------------------------------------
plt.legend()

# ------------------------------------------------------------
# Layout
# ------------------------------------------------------------
plt.tight_layout()

# ------------------------------------------------------------
# Show plot
# ------------------------------------------------------------
plt.show()

# ============================================================
# THRESHOLD SWEEP ANALYSIS
# ============================================================

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.metrics import (
    precision_score,
    recall_score,
    f1_score
)

# ------------------------------------------------------------
# Reproducibility
# ------------------------------------------------------------
np.random.seed(42)

# ------------------------------------------------------------
# Approximate test size
# ------------------------------------------------------------
total_samples = 450

# ------------------------------------------------------------
# Dataset distribution
# ------------------------------------------------------------
positive_ratio = 0.35

positive_samples = int(
    total_samples * positive_ratio
)

negative_samples = (
    total_samples - positive_samples
)

# ============================================================
# CREATE LABELS
# ============================================================

positive_labels = np.ones(
    positive_samples
)

negative_labels = np.zeros(
    negative_samples
)

labels = np.concatenate([
    positive_labels,
    negative_labels
])

# ============================================================
# CREATE SIMULATED PROBABILITIES
# ============================================================

positive_scores = np.random.normal(
    loc=0.78,
    scale=0.15,
    size=positive_samples
)

negative_scores = np.random.normal(
    loc=0.25,
    scale=0.15,
    size=negative_samples
)

scores = np.concatenate([
    positive_scores,
    negative_scores
])

# ------------------------------------------------------------
# Clamp probabilities
# ------------------------------------------------------------
scores = np.clip(
    scores,
    0,
    1
)

# ============================================================
# THRESHOLD SWEEP
# ============================================================

thresholds = np.arange(
    0.10,
    0.91,
    0.05
)

results = []

# ------------------------------------------------------------
# Evaluate each threshold
# ------------------------------------------------------------
for threshold in thresholds:

    preds = (
        scores >= threshold
    ).astype(int)

    precision = precision_score(
        labels,
        preds
    )

    recall = recall_score(
        labels,
        preds
    )

    f1 = f1_score(
        labels,
        preds
    )

    results.append([
        threshold,
        precision,
        recall,
        f1
    ])

# ============================================================
# RESULTS TABLE
# ============================================================

results_df = pd.DataFrame(

    results,

    columns=[
        "Threshold",
        "Precision",
        "Recall",
        "F1 Score"
    ]
)

# ------------------------------------------------------------
# Print results
# ------------------------------------------------------------
print("\n==========================")
print("THRESHOLD SWEEP RESULTS")
print("==========================\n")

print(
    results_df.round(4)
)

# ============================================================
# PLOT METRICS
# ============================================================

plt.figure(
    figsize=(8, 6)
)

# ------------------------------------------------------------
# Precision curve
# ------------------------------------------------------------
plt.plot(
    results_df["Threshold"],
    results_df["Precision"],
    marker="o",
    label="Precision"
)

# ------------------------------------------------------------
# Recall curve
# ------------------------------------------------------------
plt.plot(
    results_df["Threshold"],
    results_df["Recall"],
    marker="o",
    label="Recall"
)

# ------------------------------------------------------------
# F1 curve
# ------------------------------------------------------------
plt.plot(
    results_df["Threshold"],
    results_df["F1 Score"],
    marker="o",
    label="F1 Score"
)

# ------------------------------------------------------------
# Axis labels
# ------------------------------------------------------------
plt.xlabel(
    "Classification Threshold"
)

plt.ylabel(
    "Metric Value"
)

# ------------------------------------------------------------
# Title
# ------------------------------------------------------------
plt.title(
    "Threshold Sweep Analysis"
)

# ------------------------------------------------------------
# Grid
# ------------------------------------------------------------
plt.grid(
    alpha=0.3
)

# ------------------------------------------------------------
# Legend
# ------------------------------------------------------------
plt.legend()

# ------------------------------------------------------------
# Layout
# ------------------------------------------------------------
plt.tight_layout()

# ------------------------------------------------------------
# Show plot
# ------------------------------------------------------------
plt.show()

# ============================================================
# PER-CLASS METRICS
# ============================================================

import numpy as np
import pandas as pd

from sklearn.metrics import (
    classification_report
)

# ------------------------------------------------------------
# Reproducibility
# ------------------------------------------------------------
np.random.seed(42)

# ------------------------------------------------------------
# Approximate dataset size
# ------------------------------------------------------------
total_samples = 450

# ------------------------------------------------------------
# Dataset distribution
# ------------------------------------------------------------
positive_ratio = 0.35

positive_samples = int(
    total_samples * positive_ratio
)

negative_samples = (
    total_samples - positive_samples
)

# ============================================================
# CREATE LABELS
# ============================================================

# ------------------------------------------------------------
# Legitimate labels
# ------------------------------------------------------------
negative_labels = np.zeros(
    negative_samples
)

# ------------------------------------------------------------
# Trafficking labels
# ------------------------------------------------------------
positive_labels = np.ones(
    positive_samples
)

# ------------------------------------------------------------
# Combine labels
# ------------------------------------------------------------
labels = np.concatenate([
    negative_labels,
    positive_labels
])

# ============================================================
# CREATE SIMULATED PREDICTIONS
# ============================================================

# ------------------------------------------------------------
# Simulated prediction probabilities
# ------------------------------------------------------------
negative_scores = np.random.normal(
    loc=0.22,
    scale=0.15,
    size=negative_samples
)

positive_scores = np.random.normal(
    loc=0.78,
    scale=0.15,
    size=positive_samples
)

scores = np.concatenate([
    negative_scores,
    positive_scores
])

# ------------------------------------------------------------
# Clamp probabilities
# ------------------------------------------------------------
scores = np.clip(
    scores,
    0,
    1
)

# ------------------------------------------------------------
# Apply threshold
# ------------------------------------------------------------
threshold = 0.35

preds = (
    scores >= threshold
).astype(int)

# ============================================================
# CLASSIFICATION REPORT
# ============================================================

report = classification_report(

    labels,

    preds,

    target_names=[
        "Legitimate Label",
        "Trafficking Label"
    ],

    output_dict=True
)

# ------------------------------------------------------------
# Convert to dataframe
# ------------------------------------------------------------
report_df = pd.DataFrame(
    report
).transpose()

# ------------------------------------------------------------
# Round values
# ------------------------------------------------------------
report_df = report_df.round(4)

# ============================================================
# PRINT RESULTS
# ============================================================

print("\n==========================")
print("PER-CLASS METRICS")
print("==========================\n")

print(report_df)

# ============================================================
# OPTIONAL CLEAN DISPLAY
# ============================================================

metrics_df = report_df.loc[
    [
        "Legitimate Label",
        "Trafficking Label"
    ],
    [
        "precision",
        "recall",
        "f1-score",
        "support"
    ]
]

print("\n==========================")
print("CLASS-WISE PERFORMANCE")
print("==========================\n")

print(metrics_df)